import { modelFor, modelForTier } from "./models";
import { collectText, envWithApiKey, runQuery } from "./sdk-query";
import { parseFlowchart } from "./flowchart-schema";
import { parseProcedure } from "./procedure-schema";

/**
 * Dedicated artifact author. The orchestrator (Sonnet) writes a spec — what to
 * build and the concrete numbers/citations from the manual. This function runs
 * a focused sub-query that turns the spec into a production-quality artifact.
 *
 * Routing by kind:
 *   - "flowchart" → small JSON payload generated by a cheaper model (Sonnet).
 *     Rendered in the iframe by a shared React template (stepper + "show full
 *     flow" overview) so we don't re-author the same ~300 lines of stepper TSX
 *     on every emission. Validated against the schema; one retry on failure.
 *   - everything else → full code authored by Opus using the elite-author
 *     system prompt.
 *
 * The orchestrator should pick "flowchart" for any straight decision tree and
 * only fall back to "react" when the flow needs mixed interactivity
 * (calculators, charts, non-tree navigation) the template cannot express.
 */

export type ArtifactKind =
  | "react"
  | "html"
  | "svg"
  | "mermaid"
  | "markdown"
  | "flowchart"
  | "procedure";

const KIND_GUIDE: Record<ArtifactKind, string> = {
  react: `React + TSX in a sandboxed iframe. Export default function Component. Globals available without import statements: React, all hooks (useState, useEffect, useMemo, useRef, useCallback, useReducer). Imports that DO work: "recharts" (LineChart, BarChart, Tooltip, ResponsiveContainer, etc.), "lucide-react" (every icon). No other imports. Tailwind classes work — use them liberally. The iframe has no network, no localStorage, no window.parent tricks.

Design bar: this should look like a polished product, not a demo. Use spacing, typography hierarchy, subtle shadows, and rounded corners. Prefer a dark surface (bg-zinc-900 / bg-neutral-900) with high-contrast text (text-zinc-100), brand-orange accents (text-orange-400, bg-orange-500/10, border-orange-500/30) on interactive elements. Every number should have a label. Every control should have a readout. Never leave a user guessing what a slider does.`,
  html: `Standalone HTML fragment. May include <style> and <script>. Runs in a sandboxed iframe with no network. Good for trivial calculators or static layouts where React is overkill. Use inline CSS — Tailwind is NOT available here.`,
  svg: `Raw inline <svg>…</svg>. Use currentColor for strokes so it picks up the theme. Include <title> and meaningful aria-labels. ViewBox sized so it scales cleanly. Labels on every component, leader lines where helpful. Prefer thin strokes (stroke-width 1.5) and a restrained palette — white/zinc for structure, orange (#f97316) for highlights.`,
  mermaid: `Mermaid source only, no code fences. Start with "flowchart TD" or "flowchart LR" or "stateDiagram-v2". Keep node labels short (< 40 chars). Use decision diamonds for branches. Add a title with --- title: "…" ---. Note: this kind is for small at-a-glance reference diagrams only. Real decision trees and troubleshooting flows should be emitted as kind=flowchart (interactive stepper + collapsible full-flow overview via the shared template), not as static mermaid.`,
  markdown: `Long-form markdown. Use sparingly — prefer react/html for interactivity. Use headings, lists, and tables. Every factual claim must cite the source page.`,
  flowchart: `A small JSON payload that drives the shared interactive-flowchart template (stepper + collapsible "show full flow" overview). See the dedicated FLOWCHART schema section for the exact shape. Output MUST be valid JSON and nothing else.`,
  procedure: `A small JSON payload that drives the shared interactive step-by-step procedure template (Next/Previous stepper with per-step image + markdown + optional warning). See the dedicated PROCEDURE schema section for the exact shape. Output MUST be valid JSON and nothing else.`,
};

const SYSTEM_PROMPT = `You are an elite artifact author for a technical-manual assistant. You receive a SPEC describing what to build and the concrete numbers/citations extracted from the user's manual, and you output a single, complete, production-quality artifact.

YOUR OUTPUT IS THE ARTIFACT BODY AND NOTHING ELSE.
- No markdown fences, no prose, no explanation, no "Here is the…".
- First character is the first character of the code. Last character is the last.
- If asked for react, the file starts with "export default function" (or imports then the export).

QUALITY BAR
1. Visually polished. Real typography hierarchy, generous spacing, clear labels, considered color. Dark surface with orange brand accents. Looks like a shipped product.
2. Functionally complete. Every interactive control affects the output. Every computed number is labelled with its units. No placeholder TODOs, no Lorem Ipsum, no half-implemented tabs.
3. Grounded. Every number, threshold, part name, or procedure comes from the SPEC. Do NOT invent values. If the SPEC gives a range, use it. If it names a page, include the page reference in the UI (small subtle citation, mono font).
4. Self-contained. No external fetches, no images (unless SVG you generate), no fonts beyond system/tailwind defaults.

REACT-SPECIFIC RULES (these are the common failure modes — internalize them)
- Apostrophes inside single-quoted JS strings are a syntax error. Write "it's" with double quotes, or 'it\\'s' escaped. Same in JSX attribute values.
- Every JSX tag must be balanced. <div> needs </div>. <ul> needs </ul>. Components with no children MUST self-close: <Icon className="x" />, not <Icon className="x">.
- Spell every identifier the same in every reference. No "description" in one line and "deription" three lines later. Re-read every prop name and state variable before finishing.
- No raw "<" or "{" inside JSX text — escape with {"<"} and {"{"}.
- Default export is required.
- The iframe runs React 18 via sucrase (TSX→JS). Sucrase is fast but unforgiving — one stray character breaks the whole render.
- Read your output top-to-bottom before finalising. Tag stack must balance. Every brace must match. Every string must close.

INTERACTIVITY PATTERNS (when kind=react)
- Calculators: sliders + number readouts + a result panel. Show the formula. Show the manual's exact spec next to the live result.
- Troubleshooting / decision flows: you should NOT be seeing these as kind=react — they route through kind=flowchart and a shared template. You only get a flow as kind=react if the SPEC explicitly calls for mixed interactivity (embedded calculator, chart, non-tree navigation) the flowchart template can't express. In that case: the DEFAULT view is ONE step at a time (current question/check framed prominently with page citation, branch buttons labelled with the condition that triggers each branch, breadcrumb of prior answers, "start over" reset); ALONGSIDE the stepper, include a collapsible "Show full flow" panel (default collapsed) that renders the entire decision tree as a compact overview with the current node visually highlighted. Never present a static flowchart as the primary surface.
- Configurators: dropdowns with manual-accurate options, a "build summary" panel that updates live, citations under each option.
- Charts (recharts): dark theme, orange line, labelled axes with units, hover tooltips with exact values.

NEVER
- Invent facts not in the SPEC.
- Output anything besides the artifact code.
- Wrap in markdown fences.
- Add fake placeholder text like "value here" or "// TODO".
- Use fonts or assets beyond what Tailwind/CSS defaults provide.`;

const FLOWCHART_SYSTEM_PROMPT = `You are a flowchart-spec author for a technical-manual assistant. You receive a SPEC describing a decision tree or troubleshooting flow (with concrete wording, branches, and page citations from the user's manual) and you output a single valid JSON document that drives a pre-built interactive-flowchart renderer.

YOUR OUTPUT IS RAW JSON AND NOTHING ELSE.
- First character is "{". Last character is "}".
- No markdown fences, no prose, no "Here is the…", no comments.
- Do not wrap in \`\`\`json … \`\`\`.

SCHEMA
{
  "title":    string                                 // short headline, e.g. "MIG porosity troubleshooting"
  "subtitle": string?                                // optional one-line summary
  "start":    string                                 // id of the first node (must exist in "nodes")
  "nodes":    { [id: string]: Node }                 // every branch target must resolve here
  "citations": string[]?                             // optional footer citations, e.g. ["p.42", "p.58"]
}

Node = one of:

  Question node (default for decision points):
  {
    "kind": "question"
    "title":    string       // the question itself, framed directly. "Is shielding gas flowing at 20–25 CFH?"
    "detail":   string?      // one-to-three sentences of context/explanation from the manual
    "citation": string?      // "p.42" or "Quick Start p.12"
    "warning":  string?      // surfaces a safety warning as a callout on this node
    "branches": Branch[]     // 2+ branches (3+ if the manual supports it)
  }

  Action node (do this, then continue):
  {
    "kind": "action"
    "title":    string       // imperative. "Open the bottle valve and set flow to 22 CFH."
    "detail":   string?
    "citation": string?
    "warning":  string?
    "next":     string       // target node id
  }

  Terminal node (flow ends here):
  {
    "kind": "terminal"
    "title":    string       // the resolution. "Replace the liner — worn liners cause porosity."
    "detail":   string?
    "citation": string?
    "warning":  string?
    "outcome":  string?      // short tag: "Fixed", "Replace part", "Call support"
  }

Branch = {
  "label":  string           // the CONDITION that sends you here, not a generic "Yes/No" unless the question is literally binary. "Arc is unstable / sputtering" beats "Yes".
  "next":   string           // target node id
  "detail": string?          // optional longer hint shown under the button
}

QUALITY BAR
1. Grounded. Every title / detail / branch label / warning comes from the SPEC. Do NOT invent facts, part names, numbers, or procedures. If the SPEC gives an exact wording, use it.
2. Concrete branch labels. Each branch label should describe the symptom/condition the user would actually observe ("Bead is narrow and ropey", "Gas flows normally"), not a vague "Yes"/"No" unless the question is literally yes/no.
3. Page citations on every node that cites a manual fact. Keep them short ("p.42").
4. Short titles (< 100 chars) so they read well as card headings. Put detail in "detail".
5. Warnings are for safety or equipment-damage notes the manual flagged — do not cry wolf.
6. The graph must be closed: the "start" id and every "next" id must be a key in "nodes".
7. Terminal nodes are leaf outcomes. A flow must have at least one terminal node.
8. Node ids are short lowercase snake_case identifiers ("check_gas", "replace_liner").

NEVER
- Invent facts not in the SPEC.
- Output anything other than the JSON object.
- Wrap in markdown fences.
- Emit unresolved branch targets.
- Emit a flow where every path loops back on itself (there must be at least one terminal).`;

const PROCEDURE_SYSTEM_PROMPT = `You are a procedure-spec author for a technical-manual assistant. You receive a SPEC describing a linear step-by-step procedure (e.g. "loading a new wire spool") with the exact wording, photos/pages, and citations from the user's manual, and you output a single valid JSON document that drives a pre-built interactive-stepper renderer.

YOUR OUTPUT IS RAW JSON AND NOTHING ELSE.
- First character is "{". Last character is "}".
- No markdown fences, no prose, no "Here is the…", no comments.
- Do not wrap in \`\`\`json … \`\`\`.

SCHEMA
{
  "title":    string                     // short headline, e.g. "Loading a wire spool"
  "subtitle": string?                    // one-line summary, e.g. "10-step setup for 1–12 lb spools"
  "steps":    Step[]                     // ordered, 1+ steps
  "citations": string[]?                 // footer citations, e.g. ["p.10", "p.11", "p.12"]
}

Step = {
  "title":        string                 // short imperative. "Mount the spool on the spindle."
  "markdown":     string                 // body content in GitHub-flavoured markdown. Sub-steps, bullet lists, bold, inline code, short tables are encouraged. Include exact numbers, torque values, wire diameters, etc. from the SPEC.
  "imageUrl":     string?                // root-relative URL of a manual page image that illustrates this step. Usually "/sources/{doc-slug}/p-NNN.png" — the SPEC will list which page belongs to which step.
  "imageCaption": string?                // one-line caption under the image. Use it to orient the reader ("Full view of the wire feed assembly — p.15").
  "citation":     string?                // page chip shown on the step. "p.10", "Quick Start p.3".
  "warning":      string?                // surfaces a safety warning callout on the step. Use only for real safety / equipment-damage notes from the manual — do not cry wolf.
}

QUALITY BAR
1. Grounded. Every title / markdown / warning comes from the SPEC. Do NOT invent part names, torque values, diameters, or procedural steps. If the SPEC gives exact wording, use it.
2. Imperative step titles. "Mount the spool" beats "Mounting the spool". "Thread the wire through the feed rollers" beats "Wire threading".
3. Rich markdown bodies. Use numbered sub-lists for micro-steps inside a step, bullets for alternatives (e.g. "1–2 lb spool vs. 10–12 lb spool"), bold for the critical action, and inline code for exact knob names/labels when the manual styles them that way.
4. One concept per step. Do not merge "mount the spool" and "thread the wire" into a single step. Split them. 5–12 steps is a good range; fewer if the procedure is genuinely short.
5. Cite the page on every step that comes from the manual ("citation": "p.10"). Keep it short.
6. Prefer attaching an image for visually-heavy steps (mounting, threading, setting tension). Text-only steps (e.g. "power off the welder") don't need an image.
7. Warnings are for actual safety or equipment-damage notes flagged in the manual. "Power off before setup", "Do not overtighten", "Wear safety glasses".

NEVER
- Invent facts not in the SPEC.
- Output anything other than the JSON object.
- Wrap in markdown fences.
- Use imageUrl values the SPEC didn't list (no guessing page numbers).
- Collapse multi-step procedures into one giant step.`;

export async function generateArtifact(args: {
  kind: ArtifactKind;
  title: string;
  spec: string;
  priorCode?: string;
  errorContext?: string;
  signal?: AbortSignal;
  /** Per-request API key override (forwarded to the SDK subprocess env). */
  apiKey?: string;
  /** Per-request model tier override (haiku/sonnet/opus). */
  modelTier?: string;
}): Promise<string> {
  if (args.kind === "flowchart") {
    return generateFlowchart(args);
  }
  if (args.kind === "procedure") {
    return generateProcedure(args);
  }
  return generateCodeArtifact(args);
}

async function generateCodeArtifact(args: {
  kind: ArtifactKind;
  title: string;
  spec: string;
  priorCode?: string;
  errorContext?: string;
  signal?: AbortSignal;
  apiKey?: string;
  modelTier?: string;
}): Promise<string> {
  const { kind, title, spec, priorCode, errorContext } = args;

  const revisionBlock = priorCode
    ? `\n\nPRIOR VERSION (from a previous attempt — use for context, but produce a complete, new, corrected file):\n\`\`\`\n${priorCode.length > 4000 ? priorCode.slice(0, 4000) + "\n…[truncated]" : priorCode}\n\`\`\``
    : "";

  const errorBlock = errorContext
    ? `\n\nTHE PRIOR VERSION FAILED TO RENDER with this error:\n\`\`\`\n${errorContext}\n\`\`\`\nDiagnose the specific cause (syntax / typo / missing close tag / bad apostrophe) and fix it in the new version.`
    : "";

  const prompt = `Build a ${kind} artifact.

TITLE: ${title}

KIND GUIDANCE:
${KIND_GUIDE[kind]}

SPEC (from the orchestrator — what to build, and the manual numbers to embed):
---
${spec}
---${revisionBlock}${errorBlock}

Output ONLY the artifact body. No prose. No fences. No commentary. First character is code.`;

  const abort = new AbortController();
  if (args.signal) {
    args.signal.addEventListener("abort", () => abort.abort(), { once: true });
  }

  const stream = runQuery({
    prompt,
    options: {
      model: modelForTier(args.modelTier) || modelFor("qa.artifact"),
      systemPrompt: SYSTEM_PROMPT,
      allowedTools: [],
      tools: [],
      permissionMode: "bypassPermissions",
      abortController: abort,
      env: envWithApiKey(args.apiKey),
    },
  });

  const { text, error } = await collectText(stream);
  if (error) throw new Error(`artifact generation failed: ${error}`);
  if (!text) throw new Error("artifact generator returned empty output");

  return stripFences(text).trim();
}

/**
 * Flowchart path. Generates a small JSON payload (much cheaper/faster than
 * hand-authoring TSX) and validates it against the schema. On validation
 * failure, retries once with the parser error in the prompt so the model
 * can self-correct.
 */
async function generateFlowchart(args: {
  title: string;
  spec: string;
  priorCode?: string;
  errorContext?: string;
  signal?: AbortSignal;
  apiKey?: string;
  modelTier?: string;
}): Promise<string> {
  const { title, spec, priorCode, errorContext } = args;

  const basePrompt = (extraError?: string) => {
    const revisionBlock = priorCode
      ? `\n\nPRIOR VERSION (previous attempt — use for context, emit a complete new JSON):\n\`\`\`\n${priorCode.length > 4000 ? priorCode.slice(0, 4000) + "\n…[truncated]" : priorCode}\n\`\`\``
      : "";
    const priorErr = errorContext
      ? `\n\nTHE PRIOR VERSION FAILED TO RENDER with this error:\n\`\`\`\n${errorContext}\n\`\`\`\nFix the specific issue in the new JSON.`
      : "";
    const retryErr = extraError
      ? `\n\nYOUR PREVIOUS RESPONSE FAILED VALIDATION:\n\`\`\`\n${extraError}\n\`\`\`\nFix that specific issue. Output ONLY valid JSON matching the schema above.`
      : "";

    return `Build a flowchart artifact (JSON only).

TITLE: ${title}

SPEC (from the orchestrator — the flow to encode, with manual wording and citations):
---
${spec}
---${revisionBlock}${priorErr}${retryErr}

Output ONLY the JSON object. First character is "{". No prose, no fences, no commentary.`;
  };

  const runOnce = async (extraError?: string): Promise<string> => {
    const abort = new AbortController();
    if (args.signal) {
      args.signal.addEventListener("abort", () => abort.abort(), { once: true });
    }
    const stream = runQuery({
      prompt: basePrompt(extraError),
      options: {
        model: modelForTier(args.modelTier) || modelFor("qa.artifact.flowchart"),
        systemPrompt: FLOWCHART_SYSTEM_PROMPT,
        allowedTools: [],
        tools: [],
        permissionMode: "bypassPermissions",
        abortController: abort,
        env: envWithApiKey(args.apiKey),
      },
    });
    const { text, error } = await collectText(stream);
    if (error) throw new Error(`flowchart generation failed: ${error}`);
    if (!text) throw new Error("flowchart generator returned empty output");
    return stripFences(text).trim();
  };

  // First attempt.
  const first = await runOnce();
  const firstParsed = parseFlowchart(first);
  if (firstParsed.ok) {
    return JSON.stringify(firstParsed.spec);
  }

  // One self-correcting retry.
  const second = await runOnce(firstParsed.error);
  const secondParsed = parseFlowchart(second);
  if (secondParsed.ok) {
    return JSON.stringify(secondParsed.spec);
  }

  throw new Error(
    `flowchart author emitted invalid JSON after retry: ${secondParsed.error}`,
  );
}

/**
 * Procedure path. Generates a small JSON payload that the shared step-by-step
 * template renders. Same validate-and-one-retry pattern as generateFlowchart.
 */
async function generateProcedure(args: {
  title: string;
  spec: string;
  priorCode?: string;
  errorContext?: string;
  signal?: AbortSignal;
  apiKey?: string;
  modelTier?: string;
}): Promise<string> {
  const { title, spec, priorCode, errorContext } = args;

  const basePrompt = (extraError?: string) => {
    const revisionBlock = priorCode
      ? `\n\nPRIOR VERSION (previous attempt — use for context, emit a complete new JSON):\n\`\`\`\n${priorCode.length > 4000 ? priorCode.slice(0, 4000) + "\n…[truncated]" : priorCode}\n\`\`\``
      : "";
    const priorErr = errorContext
      ? `\n\nTHE PRIOR VERSION FAILED TO RENDER with this error:\n\`\`\`\n${errorContext}\n\`\`\`\nFix the specific issue in the new JSON.`
      : "";
    const retryErr = extraError
      ? `\n\nYOUR PREVIOUS RESPONSE FAILED VALIDATION:\n\`\`\`\n${extraError}\n\`\`\`\nFix that specific issue. Output ONLY valid JSON matching the schema above.`
      : "";

    return `Build a procedure artifact (JSON only).

TITLE: ${title}

SPEC (from the orchestrator — the ordered steps, per-step page image URLs, citations, warnings):
---
${spec}
---${revisionBlock}${priorErr}${retryErr}

Output ONLY the JSON object. First character is "{". No prose, no fences, no commentary.`;
  };

  const runOnce = async (extraError?: string): Promise<string> => {
    const abort = new AbortController();
    if (args.signal) {
      args.signal.addEventListener("abort", () => abort.abort(), { once: true });
    }
    const stream = runQuery({
      prompt: basePrompt(extraError),
      options: {
        model: modelForTier(args.modelTier) || modelFor("qa.artifact.procedure"),
        systemPrompt: PROCEDURE_SYSTEM_PROMPT,
        allowedTools: [],
        tools: [],
        permissionMode: "bypassPermissions",
        abortController: abort,
        env: envWithApiKey(args.apiKey),
      },
    });
    const { text, error } = await collectText(stream);
    if (error) throw new Error(`procedure generation failed: ${error}`);
    if (!text) throw new Error("procedure generator returned empty output");
    return stripFences(text).trim();
  };

  // First attempt.
  const first = await runOnce();
  const firstParsed = parseProcedure(first);
  if (firstParsed.ok) {
    return JSON.stringify(firstParsed.spec);
  }

  // One self-correcting retry.
  const second = await runOnce(firstParsed.error);
  const secondParsed = parseProcedure(second);
  if (secondParsed.ok) {
    return JSON.stringify(secondParsed.spec);
  }

  throw new Error(
    `procedure author emitted invalid JSON after retry: ${secondParsed.error}`,
  );
}

function stripFences(raw: string): string {
  const t = raw.trim();
  const fence = t.match(/^```(?:[a-zA-Z0-9_-]+)?\s*\n([\s\S]*?)\n```\s*$/);
  if (fence) return fence[1];
  return t;
}
